//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anmii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_HON
    {
        public string MAMONAN { get; set; }
        public string MAHD { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual MON_AN MON_AN { get; set; }
    }
}
