//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anmii.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLAnmiiEntities : DbContext
    {
        public QLAnmiiEntities()
            : base("name=QLAnmiiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<LOAIMONAN> LOAIMONANs { get; set; }
        public virtual DbSet<MON_AN> MON_AN { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<CHI_TIET_HOA_HON> CHI_TIET_HOA_HON { get; set; }
        public virtual DbSet<LIENHE> LIENHEs { get; set; }
    
        public virtual ObjectResult<HoaDon_ThongKe_Result> HoaDon_ThongKe(Nullable<System.DateTime> tgbd, Nullable<System.DateTime> tgkt)
        {
            var tgbdParameter = tgbd.HasValue ?
                new ObjectParameter("tgbd", tgbd) :
                new ObjectParameter("tgbd", typeof(System.DateTime));
    
            var tgktParameter = tgkt.HasValue ?
                new ObjectParameter("tgkt", tgkt) :
                new ObjectParameter("tgkt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_ThongKe_Result>("HoaDon_ThongKe", tgbdParameter, tgktParameter);
        }
    }
}
