//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anmii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_AN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MON_AN()
        {
            this.CHI_TIET_HOA_HON = new HashSet<CHI_TIET_HOA_HON>();
        }
    
        public string MAMONAN { get; set; }
        public string MALOAIMONAN { get; set; }
        public string TENMONAN { get; set; }
        public string MOTA { get; set; }
        public string ANHMONAN { get; set; }
        public Nullable<int> DONGIA { get; set; }
    
        public virtual LOAIMONAN LOAIMONAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_HOA_HON> CHI_TIET_HOA_HON { get; set; }
    }
}
